name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3

      - name: Run gofumpt
        run: gofumpt -w .

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test -coverprofile=coverage/coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/coverage.out