name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Dependencies
        run: go mod tidy

      - name: Install tools
        run: make install

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Run tests
        run: go test -bench=. ./...

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          go test -coverprofile=coverage/coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/coverage.out

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with: # Set the secret as an input
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/coverage.out
          language: go
